import os
import json
import boto3
from datetime import datetime

def main():
    """
    Simulates a creative agent generating a report and uploading it to R2.
    """
    # Get R2 credentials from environment variables
    r2_account_id = os.getenv("R2_ACCOUNT_ID")
    r2_access_key_id = os.getenv("R2_ACCESS_KEY_ID")
    r2_secret_access_key = os.getenv("R2_SECRET_ACCESS_KEY")
    r2_bucket_name = os.getenv("R2_BUCKET_NAME")

    if not all([r2_account_id, r2_access_key_id, r2_secret_access_key, r2_bucket_name]):
        print("Error: R2 environment variables are not set.")
        return

    # Create a dummy report
    report = {
        "meta": {
            "job_id": "dummy-job-123",
            "target_id": "posiblex_creative",
            "timestamp": datetime.utcnow().isoformat(),
            "status": "SUCCESS"
        },
        "visuals": {
            "summary_text": "This is a dummy report generated by the creative agent.",
            "kpi_cards": [
                {"label": "Images Processed", "value": "100"},
                {"label": "Videos Analyzed", "value": "20"},
                {"label": "Logos Generated", "value": "5"}
            ],
            "main_asset": {
                "type": "image",
                "url": "https://via.placeholder.com/800x600.png?text=Dummy+Main+Asset"
            },
            "gallery": [
                {"url": "https://via.placeholder.com/400x300.png?text=Dummy+Asset+1", "caption": "Dummy Asset 1"},
                {"url": "https://via.placeholder.com/400x300.png?text=Dummy+Asset+2", "caption": "Dummy Asset 2"}
            ]
        },
        "actions": [
            {
                "action_id": "dummy_action",
                "label": "Dummy Action",
                "endpoint_url": "/api/dummy-action",
                "requires_confirmation": True
            }
        ]
    }

    # Upload the report to R2
    try:
        s3 = boto3.client(
            "s3",
            endpoint_url=f"https://{r2_account_id}.r2.cloudflarestorage.com",
            aws_access_key_id=r2_access_key_id,
            aws_secret_access_key=r2_secret_access_key,
            region_name="auto"
        )
        report_key = f"reports/{report['meta']['job_id']}.json"
        s3.put_object(
            Bucket=r2_bucket_name,
            Key=report_key,
            Body=json.dumps(report, indent=2),
            ContentType="application/json"
        )
        print(f"Successfully uploaded report to R2: {report_key}")
    except Exception as e:
        print(f"Error uploading report to R2: {e}")

if __name__ == "__main__":
    main()
